// Regression test: pins the JS resolver ports to the legacy PHP output on 300 real `steamdb.games` rows.
//
// tests/fixtures/resolver/legacy-sample.json was generated by running the legacy gateway.php formulas
// (release date, SGG score, final time, GGP) copied verbatim, read-only, on the production DB server —
// see the throwaway script described in the task (deleted after use; nothing was written to the server).
// `now` was pinned to 2026-09-19 in that run (in place of `new DateTime()`), and the same fixed date is
// used here so the age-penalty math lines up exactly.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { legacyRelease } from '../../src/lib/resolver/release.js';
import { ggScore } from '../../src/lib/resolver/score.js';
import { finalTime } from '../../src/lib/resolver/time.js';
import { ggp } from '../../src/lib/resolver/ggp.js';
import { config } from '../../src/config.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fixturePath = path.join(__dirname, '../fixtures/resolver/legacy-sample.json');
const fixture = JSON.parse(readFileSync(fixturePath, 'utf8'));
const NOW = new Date(`${fixture.meta.now}T00:00:00Z`);

function summarize(mismatches, total) {
  const lines = [`${total - mismatches.length}/${total} matched`];
  for (const m of mismatches.slice(0, 10)) lines.push(`  id=${m.id}: expected ${JSON.stringify(m.expected)}, got ${JSON.stringify(m.actual)}`);
  if (mismatches.length > 10) lines.push(`  ... and ${mismatches.length - 10} more`);
  return lines.join('\n');
}

test(`legacy fixtures: release date (legacyRelease) matches on ${fixture.meta.count} rows`, () => {
  const mismatches = [];
  for (const row of fixture.rows) {
    const actual = legacyRelease({
      store_platform: row.input.store_platform,
      published_meta: row.input.published_meta,
      published_stsp: row.input.published_stsp,
      published_hltb: row.input.published_hltb,
      published_store: row.input.published_store,
    });
    if (actual !== row.expected.published_date) mismatches.push({ id: row.id, expected: row.expected.published_date, actual });
  }
  assert.equal(mismatches.length, 0, summarize(mismatches, fixture.rows.length));
});

test(`legacy fixtures: gg score (ggScore) matches on ${fixture.meta.count} rows`, () => {
  const mismatches = [];
  for (const row of fixture.rows) {
    const { score } = ggScore(
      {
        scoreSteam: row.input.store_uscore,
        scoreIgdb: row.input.igdb_score,
        scoreIgdbUsers: row.input.igdb_uscore,
        scoreCritics: row.input.meta_score,
        scoreUsersMetacritic: row.input.meta_uscore,
        scoreGamerankings: row.input.grnk_score,
        scoreGamefaqs: row.input.gfq_rating,
        ownersEstimate: row.input.stsp_owners,
        releaseDate: row.expected.published_date,
        genres: row.input.genres,
      },
      config.resolver.ggScore,
      NOW
    );
    // A tiny epsilon absorbs floating-point noise between PHP's and JS's arithmetic on the same formula
    // (relevant only when a single rating source is present, so legacy uses it unrounded — see fixture
    // generator comments); anything beyond that is a genuine formula mismatch.
    if (Math.abs(score - row.expected.final_score) > 1e-9) {
      mismatches.push({ id: row.id, expected: row.expected.final_score, actual: score });
    }
  }
  assert.equal(mismatches.length, 0, summarize(mismatches, fixture.rows.length));
});

test(`legacy fixtures: final time (finalTime) matches on ${fixture.meta.count} rows`, () => {
  const mismatches = [];
  for (const row of fixture.rows) {
    const result = finalTime({
      timeMain: row.input.hltb_single,
      igdbSingle: row.input.igdb_single,
      timeComplete: row.input.hltb_complete,
      igdbComplete: row.input.igdb_complete,
    });
    const expected = { finalTime: row.expected.final_time, timeComplete: row.expected.hltb_complete };
    if (result.finalTime !== expected.finalTime || result.timeComplete !== expected.timeComplete) {
      mismatches.push({ id: row.id, expected, actual: result });
    }
  }
  assert.equal(mismatches.length, 0, summarize(mismatches, fixture.rows.length));
});

test(`legacy fixtures: GGP (ggp) matches on ${fixture.meta.count} rows`, () => {
  const mismatches = [];
  for (const row of fixture.rows) {
    const time = finalTime({
      timeMain: row.input.hltb_single,
      igdbSingle: row.input.igdb_single,
      timeComplete: row.input.hltb_complete,
      igdbComplete: row.input.igdb_complete,
    });
    const { ggp: value } = ggp(
      {
        difficulty: row.input.gfq_difficulty,
        finalTime: time.finalTime,
        finalScore: row.expected.final_score,
        ownersEstimate: row.input.stsp_owners,
        priceRub: row.input.price_ru,
      },
      config.resolver.ggp
    );
    if (value !== row.expected.ggp) mismatches.push({ id: row.id, expected: row.expected.ggp, actual: value });
  }
  assert.equal(mismatches.length, 0, summarize(mismatches, fixture.rows.length));
});
